name: Build and Deploy to AWS ECS Fargate

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and Push Docker image
      id: build-image
      run: |
        # Define ECR image name and tag
        IMAGE_URI="${{ steps.login-ecr.outputs.registry }}/${{ github.repository }}:latest"
        
        # Build and push the Docker image
        docker buildx build --platform linux/amd64 --push -t $IMAGE_URI .
        
        # Output image URI
        echo "IMAGE_URI=${IMAGE_URI}" >> $GITHUB_ENV

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy to ECS
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        cluster: ${{ secrets.ECS_CLUSTER_NAME }}
        service: ${{ secrets.ECS_SERVICE_NAME }}
        task-definition: ${{ secrets.ECS_TASK_DEFINITION }}
        container-name: ${{ secrets.ECS_CONTAINER_NAME }}
        image: ${{ env.IMAGE_URI }}
        region: ${{ secrets.AWS_REGION }}
